apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  instances: 1

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-credentials

  storage:
    size: 5Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
