apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: cluster-infrastructure/authentik
        property: SECRET_KEY
    - secretKey: bootstrap-password
      remoteRef:
        key: cluster-infrastructure/authentik
        property: BOOTSTRAP_PASSWORD
    - secretKey: bootstrap-token
      remoteRef:
        key: cluster-infrastructure/authentik
        property: BOOTSTRAP_TOKEN
    - secretKey: bootstrap-email
      remoteRef:
        key: cluster-infrastructure/authentik
        property: BOOTSTRAP_EMAIL
