apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-app-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-app-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: app
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: databases/postgresql
        property: APP_PASSWORD
