apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: cluster-infrastructure/authentik
        property: POSTGRES_PASSWORD
