apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # Helm chart from Falcosecurity repository
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 4.14.2
    helm:
      values: |
        # Driver configuration - use modern_ebpf
        driver:
          enabled: true
          kind: modern_ebpf

        # Image configuration
        image:
          registry: docker.io
          repository: falcosecurity/falco-no-driver
          tag: 0.39.2

        # Resource requests
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        # Falco configuration
        falco:
          json_output: true
          json_include_output_property: true
          log_stderr: true
          log_syslog: false
          log_level: info
          rules_files:
            - /etc/falco/falco_rules.yaml
            - /etc/falco/falco_rules.local.yaml

        # Metrics
        metrics:
          enabled: true

        # Service Monitor
        serviceMonitor:
          enabled: true
          interval: 30s

        # Falcosidekick
        falcosidekick:
          enabled: true
          config:
            debug: false
          webui:
            enabled: true
            replicaCount: 1
            resources:
              requests:
                cpu: 50m
                memory: 128Mi

        # RBAC
        rbac:
          create: true

        serviceAccount:
          create: true
          name: falco

        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane

        # Extra volumes for modern_ebpf driver
        extraVolumes:
          - name: sys-fs-bpf
            hostPath:
              path: /sys/fs/bpf
              type: Directory

        extraVolumeMounts:
          - name: sys-fs-bpf
            mountPath: /sys/fs/bpf
            readOnly: false

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore StatefulSet persistentVolumeClaimRetentionPolicy differences
  # This field is set by Kubernetes but may differ from Helm chart expectations
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: falco-falcosidekick-ui-redis
      namespace: falco
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy

  revisionHistoryLimit: 10
